value:function(){var e=this.props,t=e.className,n=e.isMobile,r="zh-CN"===this.context.intl.locale;return o.a.createElement("div",{className:"home-page-wrapper banner-wrapper",id:"banner"},
o.a.createElement("div",{className:"banner-bg-wrapper"},
o.a.createElement("svg",{width:"400px",height:"576px",viewBox:"0 0 400 576",fill:"none"},
o.a.createElement(c.b,{component:"g",animation:[{opacity:0,type:"from"},b({},E,{y:15})]},
o.a.createElement("ellipse",{cx:"100",cy:"100",rx:"6",ry:"6",stroke:"#2F54EB",strokeWidth:"1.6"})),
o.a.createElement(c.b,{component:"g",animation:[{opacity:0,type:"from"},b({},E,{y:-15})]},
o.a.createElement("g",{transform:"translate(200 450)"},
o.a.createElement("g",{style:{transformOrigin:"50% 50%",transform:"rotate(-340deg)"}},
o.a.createElement("rect",{stroke:"#FADB14",strokeWidth:"1.6",width:"9",height:"9"}))))),
o.a.createElement(u.a,{location:"banner",className:"banner-bg",animation:{playScale:[1,1.5],rotate:0}})),
o.a.createElement(l.a,{className:"".concat(t," page"),type:"alpha",delay:150},